### ISSUE TITLE
Installation du barometre

### ISSUE THREAD

**Issue by Guillaume-Rossignol** [afup/barometre#176]
Bonjour,

j'essaye de suivre le pas à pas d'installation du readme, et je bloque sur le `./node_modules/bower/bin/bower install`. Globalement, il me répond : 
```
$ ./node_modules/bower/bin/bower install 
bower not-cached    git://github.com/jquery/jquery.git#1.11.0
bower resolve       git://github.com/jquery/jquery.git#1.11.0
bower not-cached    git://github.com/ivaynberg/select2.git#3.4.5
bower resolve       git://github.com/ivaynberg/select2.git#3.4.5
bower not-cached    git://github.com/twbs/bootstrap-sass.git#v3.0.3.0
bower resolve       git://github.com/twbs/bootstrap-sass.git#v3.0.3.0
bower not-cached    git://github.com/fk/select2-bootstrap-css.git#master
bower resolve       git://github.com/fk/select2-bootstrap-css.git#master
bower not-cached    git://github.com/highchartTable/jquery-highchartTable-plugin.git#~1.0.4
bower resolve       git://github.com/highchartTable/jquery-highchartTable-plugin.git#~1.0.4
bower not-cached    git://github.com/Mottie/tablesorter.git#~2.14.5
bower resolve       git://github.com/Mottie/tablesorter.git#~2.14.5
bower not-cached    git://github.com/undashes/colorbrewer.git#~1.0.0
bower resolve       git://github.com/undashes/colorbrewer.git#~1.0.0
bower not-cached    git://github.com/mbostock/d3.git#~2.10.3
bower resolve       git://github.com/mbostock/d3.git#~2.10.3
bower not-cached    git://github.com/twbs/bootstrap.git#v3.2.0
bower resolve       git://github.com/twbs/bootstrap.git#v3.2.0
bower not-cached    git://github.com/FortAwesome/Font-Awesome.git#v4.2.0
bower resolve       git://github.com/FortAwesome/Font-Awesome.git#v4.2.0
bower checkout      select2-bootstrap3-css#master
bower error         Arguments to path.join must be strings

Stack trace:                                                                                                           
TypeError: Arguments to path.join must be strings
    at Object.exports.join (path.js:384:15)
    at GitHubResolver.GitResolver._cleanup (/home/guillaume/Developpement/barometre/node_modules/bower/lib/core/resolvers/GitResolver.js:185:26)
    at /home/guillaume/Developpement/barometre/node_modules/bower/lib/core/resolvers/GitResolver.js:74:25
    at Promise.apply (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:343:11)

Console trace:
Trace
    at StandardRenderer.error (/home/guillaume/Developpement/barometre/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/home/guillaume/Developpement/barometre/node_modules/bower/bin/bower:109:18)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/guillaume/Developpement/barometre/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:808:24)
    at /home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/guillaume/Developpement/barometre/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.13.0-pre
OS: Linux 3.13-0.bpo.1-amd64 x64

```

Par contre avec le bower en version 1.3.12 installé globalement sur mon poste, ca passe niquel. Du coup, je ne sais pas si ca vient de la version de bower qui est trop vieille dans `package.json` ou si ca vient d'un autre élément de mon installation. N'etant pas famillier avec l'outil, je n'ai pas voulu proposer de modifier la version de bower sans un avis exterieur.

**Comment by BenoitLeveque** [comment]
je pense que ça viens de la version de bower, je crois bien que @agallou a le même problème.

**Comment by agallou** [comment]
oui, j'ai eut le même souci sur une nouvelle installation ce week-end. 
et oui, le passage dans la dernière version de bower corrige le problème (voici la PR : #177)
Merci @Guillaume-Rossignol pour la remontée du problème.
